pins = """
..... .....
.x... .....
..... .x...
"""

[defaults]
language = "english"
trigram_precision = 1000
keyboard_type = "ansi angle"

[weights]
heatmap = 1.65
fspeed = 12.0
lateral_penalty = 1.0
dsfb_ratio = 0.11
scissors = 4.5
lsbs = 1.5
inrolls = 1.5
outrolls = 0.2
onehands = 0.9
alternates = 0.9
alternates_sfs = 0.6
redirects = 4.0
redirects_sfs = 2.0
bad_redirects = 100
bad_redirects_sfs = 6.0

[weights.max_finger_use]
penalty = 5.0
pinky = 4.0
ring = 8.0
middle = 16.0
index = 20.0
